-- ============================================================================
--  One-time import: Ifrah's side guest list -> guests / invitations
-- ============================================================================
-- Source: Ifrah's guest-list spreadsheet ("Ifrahs ppl" tab). Run this in the
-- Supabase SQL Editor (Dashboard -> SQL Editor -> New query -> paste -> Run).
--
-- Safe to re-run: every insert is guarded so it only adds what's missing.
--   - A guest is skipped if a guest with the same name already exists
--     (compared with normalize_name(), the same case/spacing/punctuation-
--     insensitive helper the site's own search already uses).
--   - An invitation is skipped if that guest already has a row for that
--     event, so this will never duplicate or overwrite an existing RSVP.
-- Nothing already in the database is deleted, modified, or overwritten.
--
-- Everyone below is added as side = 'bride' and invited to both the Nikkah
-- and Shaadi (the two events this spreadsheet covers), with the seat count
-- ("#" column) from the spreadsheet as allowed_guest_count for each.
--
-- NOT included -- see the summary given alongside this file:
--   - "Us" (row 3, immediate family column) -- ambiguous as a guest name,
--     needs a decision on real names before it can be added.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Add any guests not already in the table (matched by normalized name)
-- ----------------------------------------------------------------------------
insert into guests (primary_guest_name, side)
select v.name, 'bride'
from (values
  ('Dada'),
  ('Baji'),
  ('Bhaiyya'),
  ('Toufiq'),
  ('Farheen'),
  ('Afreen'),
  ('Faiq'),
  ('Ali Bhai'),
  ('Siddiq bhai'),
  ('Hafeez bhai'),
  ('Rafi'),
  ('Razi'),
  ('Masiha'),
  ('Khala mami'),
  ('Haseen mami'),
  ('Abed Mamu'),
  ('Shaan Baji'),
  ('Zaki Basalath'),
  ('Amer Shafi'),
  ('Taqi Mohiuddin'),
  ('Soha Shafi'),
  ('Manha Shafi'),
  ('Maimoona'),
  ('Noori'),
  ('Najam bhai'),
  ('Vazir bhai'),
  ('Sameer Syed'),
  ('Ghouhar baji'),
  ('Zara'),
  ('Ummehani'),
  ('Shoaila'),
  ('Afzal Bhai'),
  ('Ali Khan (soha)'),
  ('Nadeem Sultan'),
  ('Sameer'),
  ('Isra'),
  ('Ibrahim'),
  ('Nousheen Bhabhi'),
  ('Najma Syed'),
  ('Ayesha Syed'),
  ('Asma Syed'),
  ('Salma Syed'),
  ('Nasia Syed'),
  ('Waseem Syed'),
  ('Aleem Syed'),
  ('Aslam Bhai'),
  ('Akram bhai'),
  ('Khurram bhai'),
  ('Farooq bhai'),
  ('Sara baji'),
  ('Sana Nikhat'),
  ('Hina Nikhat'),
  ('Sara Mir'),
  ('Maliha Azam'),
  ('Imaad'),
  ('Bakhtiya'),
  ('Shahriar'),
  ('Asfia'),
  ('Habib Bhai'),
  ('Shoaib'),
  ('Shakeeb'),
  ('Nikhat Baji'),
  ('Yasmeen Tahir'),
  ('Ayesha Lawai'),
  ('Safa Durvesh'),
  ('Isra Mohamed'),
  ('Minnah Mohideen'),
  ('Aida Adriano'),
  ('Hafsa Uddin'),
  ('Maryam Muneer'),
  ('Umnia Harb'),
  ('Rowana Zubi'),
  ('Ayah Hamdan'),
  ('Huda Yasin'),
  ('Javaria Irfan'),
  ('Moonus Sheikh'),
  ('Anasa Syeda'),
  ('Ambereen Hussain'),
  ('Iman Kadri'),
  ('Patricia Blacha'),
  ('Sania Khan'),
  ('Imaan Kazi'),
  ('AR'),
  ('Sarah Shams'),
  ('Shaymaa')
) as v(name)
where not exists (
  select 1 from guests g
  where normalize_name(g.primary_guest_name) = normalize_name(v.name)
);

-- ----------------------------------------------------------------------------
-- 2) Add any missing Nikkah/Shaadi invitations for these guests (matched by
--    normalized name against whatever is now in `guests`, whether that row
--    already existed or was just inserted above)
-- ----------------------------------------------------------------------------
insert into invitations (guest_id, event_slug, allowed_guest_count)
select g.id, x.event_slug, x.seats
from (values
  ('Dada', 1, 'nikkah'),
  ('Dada', 1, 'shaadi'),
  ('Baji', 5, 'nikkah'),
  ('Baji', 5, 'shaadi'),
  ('Bhaiyya', 5, 'nikkah'),
  ('Bhaiyya', 5, 'shaadi'),
  ('Toufiq', 4, 'nikkah'),
  ('Toufiq', 4, 'shaadi'),
  ('Farheen', 3, 'nikkah'),
  ('Farheen', 3, 'shaadi'),
  ('Afreen', 5, 'nikkah'),
  ('Afreen', 5, 'shaadi'),
  ('Faiq', 5, 'nikkah'),
  ('Faiq', 5, 'shaadi'),
  ('Ali Bhai', 4, 'nikkah'),
  ('Ali Bhai', 4, 'shaadi'),
  ('Siddiq bhai', 6, 'nikkah'),
  ('Siddiq bhai', 6, 'shaadi'),
  ('Hafeez bhai', 6, 'nikkah'),
  ('Hafeez bhai', 6, 'shaadi'),
  ('Rafi', 5, 'nikkah'),
  ('Rafi', 5, 'shaadi'),
  ('Razi', 4, 'nikkah'),
  ('Razi', 4, 'shaadi'),
  ('Masiha', 4, 'nikkah'),
  ('Masiha', 4, 'shaadi'),
  ('Khala mami', 1, 'nikkah'),
  ('Khala mami', 1, 'shaadi'),
  ('Haseen mami', 3, 'nikkah'),
  ('Haseen mami', 3, 'shaadi'),
  ('Abed Mamu', 2, 'nikkah'),
  ('Abed Mamu', 2, 'shaadi'),
  ('Shaan Baji', 2, 'nikkah'),
  ('Shaan Baji', 2, 'shaadi'),
  ('Zaki Basalath', 2, 'nikkah'),
  ('Zaki Basalath', 2, 'shaadi'),
  ('Amer Shafi', 3, 'nikkah'),
  ('Amer Shafi', 3, 'shaadi'),
  ('Taqi Mohiuddin', 6, 'nikkah'),
  ('Taqi Mohiuddin', 6, 'shaadi'),
  ('Soha Shafi', 4, 'nikkah'),
  ('Soha Shafi', 4, 'shaadi'),
  ('Manha Shafi', 2, 'nikkah'),
  ('Manha Shafi', 2, 'shaadi'),
  ('Maimoona', 5, 'nikkah'),
  ('Maimoona', 5, 'shaadi'),
  ('Noori', 11, 'nikkah'),
  ('Noori', 11, 'shaadi'),
  ('Najam bhai', 3, 'nikkah'),
  ('Najam bhai', 3, 'shaadi'),
  ('Vazir bhai', 2, 'nikkah'),
  ('Vazir bhai', 2, 'shaadi'),
  ('Sameer Syed', 2, 'nikkah'),
  ('Sameer Syed', 2, 'shaadi'),
  ('Ghouhar baji', 4, 'nikkah'),
  ('Ghouhar baji', 4, 'shaadi'),
  ('Zara', 3, 'nikkah'),
  ('Zara', 3, 'shaadi'),
  ('Ummehani', 8, 'nikkah'),
  ('Ummehani', 8, 'shaadi'),
  ('Shoaila', 5, 'nikkah'),
  ('Shoaila', 5, 'shaadi'),
  ('Afzal Bhai', 8, 'nikkah'),
  ('Afzal Bhai', 8, 'shaadi'),
  ('Ali Khan (soha)', 5, 'nikkah'),
  ('Ali Khan (soha)', 5, 'shaadi'),
  ('Nadeem Sultan', 4, 'nikkah'),
  ('Nadeem Sultan', 4, 'shaadi'),
  ('Sameer', 1, 'nikkah'),
  ('Sameer', 1, 'shaadi'),
  ('Isra', 1, 'nikkah'),
  ('Isra', 1, 'shaadi'),
  ('Ibrahim', 1, 'nikkah'),
  ('Ibrahim', 1, 'shaadi'),
  ('Nousheen Bhabhi', 4, 'nikkah'),
  ('Nousheen Bhabhi', 4, 'shaadi'),
  ('Najma Syed', 6, 'nikkah'),
  ('Najma Syed', 6, 'shaadi'),
  ('Ayesha Syed', 3, 'nikkah'),
  ('Ayesha Syed', 3, 'shaadi'),
  ('Asma Syed', 2, 'nikkah'),
  ('Asma Syed', 2, 'shaadi'),
  ('Salma Syed', 4, 'nikkah'),
  ('Salma Syed', 4, 'shaadi'),
  ('Nasia Syed', 4, 'nikkah'),
  ('Nasia Syed', 4, 'shaadi'),
  ('Waseem Syed', 5, 'nikkah'),
  ('Waseem Syed', 5, 'shaadi'),
  ('Aleem Syed', 2, 'nikkah'),
  ('Aleem Syed', 2, 'shaadi'),
  ('Aslam Bhai', 5, 'nikkah'),
  ('Aslam Bhai', 5, 'shaadi'),
  ('Akram bhai', 3, 'nikkah'),
  ('Akram bhai', 3, 'shaadi'),
  ('Khurram bhai', 4, 'nikkah'),
  ('Khurram bhai', 4, 'shaadi'),
  ('Farooq bhai', 5, 'nikkah'),
  ('Farooq bhai', 5, 'shaadi'),
  ('Sara baji', 5, 'nikkah'),
  ('Sara baji', 5, 'shaadi'),
  ('Sana Nikhat', 3, 'nikkah'),
  ('Sana Nikhat', 3, 'shaadi'),
  ('Hina Nikhat', 4, 'nikkah'),
  ('Hina Nikhat', 4, 'shaadi'),
  ('Sara Mir', 2, 'nikkah'),
  ('Sara Mir', 2, 'shaadi'),
  ('Maliha Azam', 6, 'nikkah'),
  ('Maliha Azam', 6, 'shaadi'),
  ('Imaad', 7, 'nikkah'),
  ('Imaad', 7, 'shaadi'),
  ('Bakhtiya', 4, 'nikkah'),
  ('Bakhtiya', 4, 'shaadi'),
  ('Shahriar', 5, 'nikkah'),
  ('Shahriar', 5, 'shaadi'),
  ('Asfia', 5, 'nikkah'),
  ('Asfia', 5, 'shaadi'),
  ('Habib Bhai', 5, 'nikkah'),
  ('Habib Bhai', 5, 'shaadi'),
  ('Shoaib', 6, 'nikkah'),
  ('Shoaib', 6, 'shaadi'),
  ('Shakeeb', 2, 'nikkah'),
  ('Shakeeb', 2, 'shaadi'),
  ('Nikhat Baji', 2, 'nikkah'),
  ('Nikhat Baji', 2, 'shaadi'),
  ('Yasmeen Tahir', 6, 'nikkah'),
  ('Yasmeen Tahir', 6, 'shaadi'),
  ('Ayesha Lawai', 1, 'nikkah'),
  ('Ayesha Lawai', 1, 'shaadi'),
  ('Safa Durvesh', 1, 'nikkah'),
  ('Safa Durvesh', 1, 'shaadi'),
  ('Isra Mohamed', 1, 'nikkah'),
  ('Isra Mohamed', 1, 'shaadi'),
  ('Minnah Mohideen', 1, 'nikkah'),
  ('Minnah Mohideen', 1, 'shaadi'),
  ('Aida Adriano', 1, 'nikkah'),
  ('Aida Adriano', 1, 'shaadi'),
  ('Hafsa Uddin', 1, 'nikkah'),
  ('Hafsa Uddin', 1, 'shaadi'),
  ('Maryam Muneer', 1, 'nikkah'),
  ('Maryam Muneer', 1, 'shaadi'),
  ('Umnia Harb', 1, 'nikkah'),
  ('Umnia Harb', 1, 'shaadi'),
  ('Rowana Zubi', 1, 'nikkah'),
  ('Rowana Zubi', 1, 'shaadi'),
  ('Ayah Hamdan', 1, 'nikkah'),
  ('Ayah Hamdan', 1, 'shaadi'),
  ('Huda Yasin', 1, 'nikkah'),
  ('Huda Yasin', 1, 'shaadi'),
  ('Javaria Irfan', 1, 'nikkah'),
  ('Javaria Irfan', 1, 'shaadi'),
  ('Moonus Sheikh', 1, 'nikkah'),
  ('Moonus Sheikh', 1, 'shaadi'),
  ('Anasa Syeda', 1, 'nikkah'),
  ('Anasa Syeda', 1, 'shaadi'),
  ('Ambereen Hussain', 1, 'nikkah'),
  ('Ambereen Hussain', 1, 'shaadi'),
  ('Iman Kadri', 1, 'nikkah'),
  ('Iman Kadri', 1, 'shaadi'),
  ('Patricia Blacha', 1, 'nikkah'),
  ('Patricia Blacha', 1, 'shaadi'),
  ('Sania Khan', 1, 'nikkah'),
  ('Sania Khan', 1, 'shaadi'),
  ('Imaan Kazi', 5, 'nikkah'),
  ('Imaan Kazi', 5, 'shaadi'),
  ('AR', 2, 'nikkah'),
  ('AR', 2, 'shaadi'),
  ('Sarah Shams', 1, 'nikkah'),
  ('Sarah Shams', 1, 'shaadi'),
  ('Shaymaa', 1, 'nikkah'),
  ('Shaymaa', 1, 'shaadi')
) as x(name, seats, event_slug)
join guests g
  on normalize_name(g.primary_guest_name) = normalize_name(x.name)
where not exists (
  select 1 from invitations i
  where i.guest_id = g.id and i.event_slug = x.event_slug
);
