-- ============================================================================
--  One-time import: Ifrah's side guest list -> guests / invitations
-- ============================================================================
-- Source: Ifrah's guest-list spreadsheet ("Ifrahs ppl" tab, corrected names).
-- Run this in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run).
--
-- Safe to re-run: every insert is guarded so it only adds what's missing.
--   - A guest is skipped if a guest with the same name already exists
--     (compared with normalize_name(), the same case/spacing/punctuation-
--     insensitive helper the site's own search already uses).
--   - An invitation is skipped if that guest already has a row for that
--     event, so this will never duplicate or overwrite an existing RSVP.
-- Nothing already in the database is deleted, modified, or overwritten.
--
-- Everyone below is added as side = 'bride' and invited to both the Nikkah
-- and Shaadi (the two events this spreadsheet covers), with the seat count
-- ("#" column) from the spreadsheet as allowed_guest_count for each.
--
-- NOT included -- see the summary given alongside this file:
--   - Both "Ayesha Syed" entries (Immediate fam, 5 seats, and Not Chicago,
--     3 seats) -- two different people with the identical name. Adding both
--     as-is would be genuinely ambiguous, not just for this script but for
--     the RSVP site itself: if two guests share an exact name and are
--     invited to the same events, the "we found a few matches" screen a
--     real guest sees has no way to tell them apart. Needs a distinguishing
--     name (e.g. a middle name or different name) for at least one of them
--     before either can be added.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Add any guests not already in the table (matched by normalized name)
-- ----------------------------------------------------------------------------
insert into guests (primary_guest_name, side)
select v.name, 'bride'
from (values
  ('Safdar Ali'),
  ('Mohammed Imtiyaz'),
  ('Fouzia Fatima'),
  ('Tahmina Fatima'),
  ('Mohammed Ali'),
  ('Ali Mohammad'),
  ('Siddiq Mohammad'),
  ('Hafeez Mohammad'),
  ('Rafi Mohammed'),
  ('Razi Mohammed'),
  ('Masiha Iffat'),
  ('Afzal Syed'),
  ('Haseen Syed'),
  ('Abed Syed'),
  ('Shaan Khan'),
  ('Zaki Basalath'),
  ('Amer Shafi'),
  ('Taqi Mohiuddin'),
  ('Soha Shafi'),
  ('Manha Shafi'),
  ('Maimoona Zubair'),
  ('Nooran Hashmi'),
  ('Najam Syed'),
  ('Vazir Syed'),
  ('Sameer Syed'),
  ('Ghouhar Mohammed'),
  ('Zara'),
  ('Ummehani'),
  ('Shoaila'),
  ('Afzal Bhai'),
  ('Ali Khan'),
  ('Nadeem Sultan'),
  ('Sameer AbdulRaheem'),
  ('Isra Meraj'),
  ('Ibrahim Rahman'),
  ('Nousheen Bhabhi'),
  ('Najma Syed'),
  ('Asma Syed'),
  ('Salma Syed'),
  ('Nasia Syed'),
  ('Waseem Syed'),
  ('Aleem Syed'),
  ('Aslam Syed'),
  ('Akram Syed'),
  ('Khurram Syed'),
  ('Farooq bhai'),
  ('Sara Syed'),
  ('Sana Nikhat'),
  ('Hina Nikhat'),
  ('Sara Mir'),
  ('Maliha Azam'),
  ('Imaad Syed'),
  ('Baqtiar Mohammed'),
  ('Shahriar Mohammed'),
  ('Asfia Mohammed'),
  ('Habib Bhai'),
  ('Shoaib Mohammed'),
  ('Shakeeb Mohammed'),
  ('Mohsin Nikhat'),
  ('Farhath Vardhan'),
  ('Yasmeen Tahir'),
  ('Ayesha Lawai'),
  ('Safa Durvesh'),
  ('Isra Mohamed'),
  ('Minnah Mohideen'),
  ('Aida Adriano'),
  ('Hafsa Uddin'),
  ('Maryam Muneer'),
  ('Umnia Harb'),
  ('Rowana Zubi'),
  ('Ayah Hamdan'),
  ('Huda Yasin'),
  ('Javaria Irfan'),
  ('Moonus Sheikh'),
  ('Anasa Syeda'),
  ('Ambereen Hussain'),
  ('Iman Kadri'),
  ('Patricia Blacha'),
  ('Sania Khan'),
  ('Imaan Kazi'),
  ('Abdul Rahman'),
  ('Sarah Shams'),
  ('Shaymaa')
) as v(name)
where not exists (
  select 1 from guests g
  where normalize_name(g.primary_guest_name) = normalize_name(v.name)
);

-- ----------------------------------------------------------------------------
-- 2) Add any missing Nikkah/Shaadi invitations for these guests (matched by
--    normalized name against whatever is now in `guests`, whether that row
--    already existed or was just inserted above)
-- ----------------------------------------------------------------------------
insert into invitations (guest_id, event_slug, allowed_guest_count)
select g.id, x.event_slug, x.seats
from (values
  ('Safdar Ali', 5, 'nikkah'),
  ('Safdar Ali', 5, 'shaadi'),
  ('Mohammed Imtiyaz', 4, 'nikkah'),
  ('Mohammed Imtiyaz', 4, 'shaadi'),
  ('Fouzia Fatima', 3, 'nikkah'),
  ('Fouzia Fatima', 3, 'shaadi'),
  ('Tahmina Fatima', 5, 'nikkah'),
  ('Tahmina Fatima', 5, 'shaadi'),
  ('Mohammed Ali', 5, 'nikkah'),
  ('Mohammed Ali', 5, 'shaadi'),
  ('Ali Mohammad', 4, 'nikkah'),
  ('Ali Mohammad', 4, 'shaadi'),
  ('Siddiq Mohammad', 6, 'nikkah'),
  ('Siddiq Mohammad', 6, 'shaadi'),
  ('Hafeez Mohammad', 6, 'nikkah'),
  ('Hafeez Mohammad', 6, 'shaadi'),
  ('Rafi Mohammed', 5, 'nikkah'),
  ('Rafi Mohammed', 5, 'shaadi'),
  ('Razi Mohammed', 4, 'nikkah'),
  ('Razi Mohammed', 4, 'shaadi'),
  ('Masiha Iffat', 4, 'nikkah'),
  ('Masiha Iffat', 4, 'shaadi'),
  ('Afzal Syed', 1, 'nikkah'),
  ('Afzal Syed', 1, 'shaadi'),
  ('Haseen Syed', 3, 'nikkah'),
  ('Haseen Syed', 3, 'shaadi'),
  ('Abed Syed', 2, 'nikkah'),
  ('Abed Syed', 2, 'shaadi'),
  ('Shaan Khan', 2, 'nikkah'),
  ('Shaan Khan', 2, 'shaadi'),
  ('Zaki Basalath', 2, 'nikkah'),
  ('Zaki Basalath', 2, 'shaadi'),
  ('Amer Shafi', 3, 'nikkah'),
  ('Amer Shafi', 3, 'shaadi'),
  ('Taqi Mohiuddin', 6, 'nikkah'),
  ('Taqi Mohiuddin', 6, 'shaadi'),
  ('Soha Shafi', 4, 'nikkah'),
  ('Soha Shafi', 4, 'shaadi'),
  ('Manha Shafi', 2, 'nikkah'),
  ('Manha Shafi', 2, 'shaadi'),
  ('Maimoona Zubair', 5, 'nikkah'),
  ('Maimoona Zubair', 5, 'shaadi'),
  ('Nooran Hashmi', 11, 'nikkah'),
  ('Nooran Hashmi', 11, 'shaadi'),
  ('Najam Syed', 3, 'nikkah'),
  ('Najam Syed', 3, 'shaadi'),
  ('Vazir Syed', 2, 'nikkah'),
  ('Vazir Syed', 2, 'shaadi'),
  ('Sameer Syed', 2, 'nikkah'),
  ('Sameer Syed', 2, 'shaadi'),
  ('Ghouhar Mohammed', 4, 'nikkah'),
  ('Ghouhar Mohammed', 4, 'shaadi'),
  ('Zara', 3, 'nikkah'),
  ('Zara', 3, 'shaadi'),
  ('Ummehani', 8, 'nikkah'),
  ('Ummehani', 8, 'shaadi'),
  ('Shoaila', 5, 'nikkah'),
  ('Shoaila', 5, 'shaadi'),
  ('Afzal Bhai', 8, 'nikkah'),
  ('Afzal Bhai', 8, 'shaadi'),
  ('Ali Khan', 5, 'nikkah'),
  ('Ali Khan', 5, 'shaadi'),
  ('Nadeem Sultan', 4, 'nikkah'),
  ('Nadeem Sultan', 4, 'shaadi'),
  ('Sameer AbdulRaheem', 1, 'nikkah'),
  ('Sameer AbdulRaheem', 1, 'shaadi'),
  ('Isra Meraj', 1, 'nikkah'),
  ('Isra Meraj', 1, 'shaadi'),
  ('Ibrahim Rahman', 1, 'nikkah'),
  ('Ibrahim Rahman', 1, 'shaadi'),
  ('Nousheen Bhabhi', 4, 'nikkah'),
  ('Nousheen Bhabhi', 4, 'shaadi'),
  ('Najma Syed', 6, 'nikkah'),
  ('Najma Syed', 6, 'shaadi'),
  ('Asma Syed', 2, 'nikkah'),
  ('Asma Syed', 2, 'shaadi'),
  ('Salma Syed', 4, 'nikkah'),
  ('Salma Syed', 4, 'shaadi'),
  ('Nasia Syed', 4, 'nikkah'),
  ('Nasia Syed', 4, 'shaadi'),
  ('Waseem Syed', 5, 'nikkah'),
  ('Waseem Syed', 5, 'shaadi'),
  ('Aleem Syed', 2, 'nikkah'),
  ('Aleem Syed', 2, 'shaadi'),
  ('Aslam Syed', 5, 'nikkah'),
  ('Aslam Syed', 5, 'shaadi'),
  ('Akram Syed', 3, 'nikkah'),
  ('Akram Syed', 3, 'shaadi'),
  ('Khurram Syed', 4, 'nikkah'),
  ('Khurram Syed', 4, 'shaadi'),
  ('Farooq bhai', 5, 'nikkah'),
  ('Farooq bhai', 5, 'shaadi'),
  ('Sara Syed', 5, 'nikkah'),
  ('Sara Syed', 5, 'shaadi'),
  ('Sana Nikhat', 3, 'nikkah'),
  ('Sana Nikhat', 3, 'shaadi'),
  ('Hina Nikhat', 4, 'nikkah'),
  ('Hina Nikhat', 4, 'shaadi'),
  ('Sara Mir', 2, 'nikkah'),
  ('Sara Mir', 2, 'shaadi'),
  ('Maliha Azam', 6, 'nikkah'),
  ('Maliha Azam', 6, 'shaadi'),
  ('Imaad Syed', 7, 'nikkah'),
  ('Imaad Syed', 7, 'shaadi'),
  ('Baqtiar Mohammed', 4, 'nikkah'),
  ('Baqtiar Mohammed', 4, 'shaadi'),
  ('Shahriar Mohammed', 5, 'nikkah'),
  ('Shahriar Mohammed', 5, 'shaadi'),
  ('Asfia Mohammed', 5, 'nikkah'),
  ('Asfia Mohammed', 5, 'shaadi'),
  ('Habib Bhai', 5, 'nikkah'),
  ('Habib Bhai', 5, 'shaadi'),
  ('Shoaib Mohammed', 6, 'nikkah'),
  ('Shoaib Mohammed', 6, 'shaadi'),
  ('Shakeeb Mohammed', 2, 'nikkah'),
  ('Shakeeb Mohammed', 2, 'shaadi'),
  ('Mohsin Nikhat', 2, 'nikkah'),
  ('Mohsin Nikhat', 2, 'shaadi'),
  ('Farhath Vardhan', 4, 'nikkah'),
  ('Farhath Vardhan', 4, 'shaadi'),
  ('Yasmeen Tahir', 6, 'nikkah'),
  ('Yasmeen Tahir', 6, 'shaadi'),
  ('Ayesha Lawai', 1, 'nikkah'),
  ('Ayesha Lawai', 1, 'shaadi'),
  ('Safa Durvesh', 1, 'nikkah'),
  ('Safa Durvesh', 1, 'shaadi'),
  ('Isra Mohamed', 1, 'nikkah'),
  ('Isra Mohamed', 1, 'shaadi'),
  ('Minnah Mohideen', 1, 'nikkah'),
  ('Minnah Mohideen', 1, 'shaadi'),
  ('Aida Adriano', 1, 'nikkah'),
  ('Aida Adriano', 1, 'shaadi'),
  ('Hafsa Uddin', 1, 'nikkah'),
  ('Hafsa Uddin', 1, 'shaadi'),
  ('Maryam Muneer', 1, 'nikkah'),
  ('Maryam Muneer', 1, 'shaadi'),
  ('Umnia Harb', 1, 'nikkah'),
  ('Umnia Harb', 1, 'shaadi'),
  ('Rowana Zubi', 1, 'nikkah'),
  ('Rowana Zubi', 1, 'shaadi'),
  ('Ayah Hamdan', 1, 'nikkah'),
  ('Ayah Hamdan', 1, 'shaadi'),
  ('Huda Yasin', 1, 'nikkah'),
  ('Huda Yasin', 1, 'shaadi'),
  ('Javaria Irfan', 1, 'nikkah'),
  ('Javaria Irfan', 1, 'shaadi'),
  ('Moonus Sheikh', 1, 'nikkah'),
  ('Moonus Sheikh', 1, 'shaadi'),
  ('Anasa Syeda', 1, 'nikkah'),
  ('Anasa Syeda', 1, 'shaadi'),
  ('Ambereen Hussain', 1, 'nikkah'),
  ('Ambereen Hussain', 1, 'shaadi'),
  ('Iman Kadri', 1, 'nikkah'),
  ('Iman Kadri', 1, 'shaadi'),
  ('Patricia Blacha', 1, 'nikkah'),
  ('Patricia Blacha', 1, 'shaadi'),
  ('Sania Khan', 1, 'nikkah'),
  ('Sania Khan', 1, 'shaadi'),
  ('Imaan Kazi', 5, 'nikkah'),
  ('Imaan Kazi', 5, 'shaadi'),
  ('Abdul Rahman', 2, 'nikkah'),
  ('Abdul Rahman', 2, 'shaadi'),
  ('Sarah Shams', 1, 'nikkah'),
  ('Sarah Shams', 1, 'shaadi'),
  ('Shaymaa', 1, 'nikkah'),
  ('Shaymaa', 1, 'shaadi')
) as x(name, seats, event_slug)
join guests g
  on normalize_name(g.primary_guest_name) = normalize_name(x.name)
where not exists (
  select 1 from invitations i
  where i.guest_id = g.id and i.event_slug = x.event_slug
);
